### ISSUE TITLE
PICO LED not detected by watch sensor.

### ISSUE THREAD

**Issue by Kup86** [famiclone6502/DIY_Datalink_Adapter#2] opened 2022-08-19 08:32 UTC
Hi :)

I tried the Pico out and the script went in well, the VM (or DOSBOX) detects the the serial passthrough fine. The Datalink Software also works well in the sense that the device is detected as a Datalink adapter and the green LED starts to flash.

The problem is that the LED is not picked up at all by my watch as it may be too weak or wrong intensity. To the human eye seems fine and bright though.

Technically everything appears to work well, the Pico led flashes at what looks like to be the right sequence. However it may be to weak or wrong type for the watch to pick up. It is possible that different batches of PICOs have different LED types if yours worked well.

I am using the same model PICO as yours, not the W wifi one.

If my theory that not all LEDs are the same for the same model Picos is correct - May I suggest assigning a couple of of the GPIO ports/holes for +/- so that a peripheral LED can be attached. Yeah it would lose the 'no extra hardware needed' feature but it would still be a minor requirement and work around if anyone encounters the same issue.

Edit: After I wrote the above, I gave it several other goes and got it to work. My theory of 'weak' LED might be sound as I can only get it to work by literally pressing the watch sensor into the LED and even so, it has to be at a particular angle to the 'circle' of the sensor. It is not super practical as it only has a sweetspot of like 1mm so its really hard to find the same angle again and held very still - But it works :)

The Arduino version still works well and is very forgiving of angle/distance so I don't think its the watch in this case.

Once again - Great work!

**Comment by famiclone6502** [comment] 2022-08-19 13:53
The Pico version does need the watch closer than the Arduino version. Mine pictured in the readme shows how close it may work, but I did have to shield it more from interference (monitor, lights). 

The change needed for an external LED is commented in the code, I just haven't provided a precompiled version with that feature. It could even be changed to use serial instead of USB, but I wanted to keep the Pico version as simple as possible even if it's not ideal.

**Comment by Kup86** [comment] 2022-08-19 15:32
Yeah the idea of keeping the Pico as simple as possible (no serial) is still excellent. I wouldn't change it, specially when you already have the arduino option.

**Comment by famiclone6502** [comment] 2022-08-19 16:19
Thanks for confirming! I'm going to close this issue, as it's working as designed. While not ideal, it works. 

There are now Pico clones on Aliexpress that have a much brighter LED on GPIO 23. But it may need some additional code changes since it's an RGB LED.

**Closed by famiclone6502** 2022-08-19 16:19 UTC

**Comment by famiclone6502** [comment] 2023-01-19 22:08
Per your suggestion, I've published a version now that simultaneously blinks an external LED on the Pico if connected to GPIO port 18. This is optional for anyone having issues with the original Pico, but would be required for Pico W users due to hardware differences.
